# Generated by Django 4.2.2 on 2023-06-27 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='fk_folder',
            new_name='folder',
        ),
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
